### ISSUE TITLE
Profile page title is not correct

### ISSUE THREAD

**Issue by cait-g1** [cait-g1/sahel-support#1]
**Describe the bug**
Text issue
Describe the bug briefly. 
The title should be “هوية المستخدم"
**To Reproduce**
1. Logged as civil id: 
2. On page: Identity top right
3. Clicked on: 

**Resulted error**
Describe error or error message.
Showing “إعدادات"
**Expected behavior**
"هوية المستخدم"

**Screenshots**

**Device info (please complete the following information):**
 - OS: [e.g. iOS, Android]
 - Device name [iPhone 8, Galaxy Note]
 - Sahel Version [e.g. 0.3.9+12  (12 is build number or version code

**Additional context**

**Comment by KLD** [comment]
Will be fixed in next released
