### ISSUE TITLE
App freezing after taping the new notification in status bar 

### ISSUE THREAD

**Issue by aboabdelaziz** [cait-g1/sahel-support#11]
**Describe the bug**
The app gets freezing after tapping the new notification in status bar

**To Reproduce**
1. Logged as civil id: 275062301151
2. On page: notifications
![Screenshot_20200628-200045](https://user-images.githubusercontent.com/36797115/85955339-8963d980-b986-11ea-8e00-5ad4ddb0ee8f.jpg)

3. Clicked on: notification icon in the status bar

**Resulted error**
App freezing

**Expected behavior**
Display the notifications section in the app including the new recieved one

**Device info**
 - OS: [Android]
 - Device name [Galaxy S8]
 - Sahel Version [0.5.0]

**Comment by KLD** [comment]
Version 0.5.0 is deprecated. A new version is pending release. Expect it within two days.

**Comment by aboabdelaziz** [comment]
The bug is still present.. With the new build 0.4.1(43)

**Comment by KLD** [comment]
Just confirmed the bug. ~Since it's critical, an update will be deployed as soon as possible~

Edit: the critical bug was different than this. Next update (above 0.4.1+44) will patch it up.
