### ISSUE TITLE
Server error 

### ISSUE THREAD

**Issue by aboabdelaziz** [cait-g1/sahel-support#5]
![Screenshot_20200513-115855](https://user-images.githubusercontent.com/36797115/81793891-a3e70e00-9512-11ea-9078-bd24b2cb8d7d.jpg)

**Comment by KLD** [comment]
I'll assume this happen when you exit 'الجهات الحكومية'  to follow or unfollow. 
If so, issue is identified, and will be fixed next released. 

If not, please provide details about how to reproduce this.

**Comment by aboabdelaziz** [comment]
Actually, this error appears mostly everywhere, nothing is functioning in the app.. The only function that works is user profile!

And sometimes I got that error randomly, for example once the app is open and when try to refresh the service status tab

**Comment by KLD** [comment]
Just checking if this is issue is resolved, so I can close it. 

If it persist, please provide me your civil id so I can investigate further.

**Comment by aboabdelaziz** [comment]
Yes, it's still persist, and here's my civil id: 275062301151

**Comment by Mohd-3** [comment]
Issue is fixed, closing.
