### ISSUE TITLE
POST submit error "NOT FOUND: The requested resource was not found on this server"

### ISSUE THREAD

**Issue by sdhuayyan** [cait-g1/sahel-support#6]
### IMPORTNANT 
DO NOT share any secrets or keys here, please blur them when reporting. If necessary, you may show part of the secret that deems it identifiable **at your own risk**. 

**Describe the bug**
After POST is sent i get this error message.

**To Reproduce (please complete the following information)**
1. Go to POST 
2. add new POST.
3. submit POST 
4. Response Status Code: Not Found: The requested resource was not found on this server.

**Expected behavior**
massage confirming the post submission.

**Screenshots**
![image](https://user-images.githubusercontent.com/60649094/81906658-4238a980-95cf-11ea-9035-d1ade6aab84e.png)

**Additional context**

**Comment by Mohd-3** [comment]
Issue is fixed, closing.
