### ISSUE TITLE
Post Notification in Background

### ISSUE THREAD

**Issue by cait-g1** [cait-g1/sahel-support#9]
**Describe the bug**
When a Post Notification is received while App in Background the Post is not received

**Expected behavior**
The new Post must show in the list

**Device info (please complete the following information):**
 - OS: iOS
 - Device name iPhone 11
 - Sahel Version 0.5.0(29)

**Comment by Mohd-3** [comment]
Added in dev and it is working for post/public post, just waiting for mobile app release with no-refresh service status and it will work for service status too.
